config/routes.rb
Rails.application.routes.draw do
  root 'meals#index'

  resources :meals
end

app/models/meal.rb
class Meal
  attr_accessor :record_id, :name, :description, :rating, :category

  def initialize(data)
    @record_id = data["record_id_"].to_i
    @name = data["name"]
    @description = data["description"]
    @rating = data["rating"].to_f
    @category = data["category"]
  end

  def self.service
    @service ||= QuickbaseService.new
  end

  def self.all
    service.find_all.map { |record| build_meal(record) }
  end

  def self.find(id)
    build_meal(service.find_by_record_id(id))
  end

  def self.create(data)
    service.create_record(data)
  end

  def self.update(id, data)
    service.update_record(id, data)
  end

  def self.delete(id)
    service.delete_record(id)
  end

  private

  def self.build_meal(data)
    Meal.new(data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params["id"])
  end

  def new
  end

  def create
    response = Meal.create(meal_params)
    meal_id = response["qdbapi"]["rid"]
    flash[:notice] = "You added a meal"
    redirect_to meal_path(meal_id)
  end

  def edit
    @meal = Meal.find(params["id"])
  end

  def update
    Meal.update(params["id"], meal_params)
    flash[:notice] = "You updated this meal"
    redirect_to meal_path(params["id"])
  end

  def destroy
    meal_id = params["id"]
    Meal.delete(meal_id)
    flash[:notice] = "You deleted a meal"
    redirect_to meals_path
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :description, :rating, :category)
  end
end

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
  <div class="column-group">
    <div class="all-20"></div>
    <div class="all-60">
      <div class="ink-alert basic success" role="alert">
        <button class="ink-dismiss">&times;</button>
          <% flash.each do |key, message| %>
            <%= message %>
          <% end %>
      </div>
    </div>
    <div class="all-20"></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealWorldQuickbase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container" class="ink-grid">
  <%= render 'layouts/notices' %>
  <%= yield %>
</div>

</body>
</html>

app/views/meals/edit.html.erb
<div class="header">
  <h1>Editing <%= @meal.name %>
  <span class="cta push-right"><%= link_to "Back to this meal", meal_path(@meal.record_id) %></span>
  </h1>
</div>

<%= form_tag("/meals/#{@meal.record_id}", method: :put, class: "ink-form") do %>
  <div class="control-group">
      <%= label_tag(:name, "Meal name") %>
    <div class="control">
      <%= text_field(:meal, :name) %>
    </div>

    <%= label_tag(:description, "Describe it") %>
    <div class="control">
      <%= text_area(:meal, :description) %>
    </div>

    <%= label_tag(:category, "Category") %>
    <div class="control">
      <%= text_field(:meal, :category) %>
    </div>

    <%= label_tag(:rating, "Rating") %>
    <div class="control">
      <%= number_field(:meal, :rating, in: 1...6) %>
    </div>

    <hr>

    <div class="control">
      <%= submit_tag("Update meal", class: "ink-button green") %>
    </div>
  </div>
<% end %>

app/views/meals/index.html.erb
<div class="header">
  <h1>Your Meals
  <span class="cta push-right"><%= link_to "What did you eat today?", new_meal_path %></span>
</h1>
</div>

<div class="column-group horizontal-gutters">
<% @meals.each do |meal| %>
    <div id="meal-box" class="all-33">
      <h3><%= meal.name %></h3>
      <p>Rating: <%= meal.rating %></p>
      <p><%= link_to "Meal details", meal_path(meal.record_id) %>
    </div>
<% end %>
</div>

app/views/meals/new.html.erb
<div class="header">
  <h1>New Meal
  <span class="cta push-right"><%= link_to "Back to all meals", meals_path %></span>
  </h1>
</div>
  <%= form_tag('/meals', class: "ink-form") do %>
    <div class="control-group">
      <%= label_tag(:name, "Meal name") %>
      <div class="control">
        <%= text_field(:meal, :name) %>
      </div>

      <%= label_tag(:description, "Describe it") %>
      <div class="control">
        <%= text_area(:meal, :description) %>
      </div>

      <%= label_tag(:category, "Category") %>
      <div class="control">
        <%= text_field(:meal, :category) %>
      </div>

      <%= label_tag(:rating, "Rating") %>
      <div class="control">
        <%= number_field(:meal, :rating, in: 1...6) %>
      </div>

      <hr>

      <div class="control">
        <%= submit_tag("Add meal", class: "ink-button green") %>
      </div>
    </div>
  <% end %>

app/views/meals/show.html.erb
<div class="header">
  <h1><%= @meal.name %>
  <span class="cta push-right"><%= link_to "Back to all meals", meals_path %></span>
  </h1>
</div>

<div class="column-group">
  <div class="all-60">
    <p class="medium">Category</p>
    <p><%= @meal.category %></p>
    <p class="medium">Description</p>
    <p><%= @meal.description %></p>
    <p class="medium">Rating</p>
    <p><%= @meal.rating %></p>
  </div>
  <div class="all-40">
    <div class="button-group">
      <p><%= link_to "Edit meal", edit_meal_path(@meal.record_id), class: "ink-button green" %></p>
      <hr>
      <%= button_to "Delete #{@meal.name}", meal_path(@meal.record_id), method: :delete, data: { confirm: 'Are you sure?' }, class: "ink-button green" %>
    </div>
  </div>
</div>